import {
  Plane,
  MapPin,
  DollarSign,
  Calendar,
  Bike,
  Soup,
  Pyramid,
  Wifi,
  Languages,
  TrainFront,
  Shield,
  FerrisWheel,
  BookOpenCheck,
  Car,
  Hotel,
  Utensils,
  ShoppingBag,
  Sun,
  Clock,
  Pin,
  Leaf,
  Building,
  Check,
  CalendarCheck,
  Backpack,
  CableCar,
  Store,
  Sailboat,
  Coffee,
  Sandwich,
  Salad,
  IceCream,
  Star,
  Wine,
  Info,
  Cookie,
} from "lucide-react";

export const ICONS = {
  PYRAMID: Pyramid,
  PLANE: Plane,
  MAP_PIN: MapPin,
  DOLLAR_SIGN: DollarSign,
  CALENDAR: Calendar,
  WIFI: Wifi,
  LANGUAGES: Languages,
  TRAIN_FRONT: TrainFront,
  BIKE: Bike,
  SOUP: Soup,
  SHIELD: Shield,
  FERRIS_WHEEL: FerrisWheel,
  BOOK_OPEN_CHECK: BookOpenCheck,
  CAR: Car,
  HOTEL: Hotel,
  FOOD: Utensils,
  SHOPPING: ShoppingBag,
  SUN: Sun,
  CLOCK: Clock,
  PIN: Pin,
  LEAF: Leaf,
  BUILDING: Building,
  CHECK: Check,
  CALENDAR_CHECK: CalendarCheck,
  BACKPACK: Backpack,
  CABLE_CAR: CableCar,
  STORE: Store,
  SAILBOAT: Sailboat,
  COFFEE: Coffee,
  LUNCH: Utensils,
  STREET_FOOD: Sandwich,
  VEGETARIAN: Salad,
  DRINKS: Soup,
  DESSERTS: IceCream,
  SIDES: Star,
  SANDWICH: Sandwich,
  PLACES: Building,
  ALCOHOL: Wine,
  QUICK_TIPS: BookOpenCheck,
  COOKIE: Cookie,
};
